baseURL = "https://ttlzero.pages.dev"
languageCode = "en-us"
title = "TTL Zero - Tech Blog"
theme = "PaperMod"

[params]
env = "production"
title = "TTL Zero"
description = "Network automation, DevOps, and development insights"
keywords = ["networking", "automation", "devops", "programming", "tech"]
author = "Your Name"

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowToc = true
TocOpen = false

# Fix for the SiteVerificationTag error
googleSiteVerificationTag = ""
bingSiteVerificationTag = ""

images = ["avatar.png"]

    [params.homeInfoParams]
    Title = "Welcome to TTL Zero"
    Content = "Network automation, DevOps insights, and development tutorials. When packets expire, knowledge begins."

[[params.socialIcons]]
name = "github"
url = "https://github.com/yourusername"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/yourusername"

[menu]
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

# Markup configuration
[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
